//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acivator_Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acivator_Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @set masver=2.5
        ///@setlocal DisableDelayedExpansion
        ///@echo off
        ///
        ///
        ///
        ///::============================================================================
        ///::
        ///::   This script is a part of &apos;Microsoft_Activation_Scripts&apos; (MAS) project.
        ///::
        ///::   Homepage: mass grave[.]dev
        ///::      Email: windowsaddict@protonmail.com
        ///::
        ///::============================================================================
        ///
        ///
        ///
        ///::  To activate, run the script with &quot;/HWID&quot; parameter or change 0 to 1 in below line
        ///set _act=0
        ///
        ///::  To di [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string HWID_Activation {
            get {
                return ResourceManager.GetString("HWID_Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @set masver=2.5
        ///@setlocal DisableDelayedExpansion
        ///@echo off
        ///
        ///
        ///
        ///::============================================================================
        ///::
        ///::   This script is a part of &apos;Microsoft_Activation_Scripts&apos; (MAS) project.
        ///::
        ///::   Homepage: mass grave[.]dev
        ///::      Email: windowsaddict@protonmail.com
        ///::
        ///::============================================================================
        ///
        ///
        ///
        ///::  To activate, run the script with &quot;/KMS38&quot; parameter or change 0 to 1 in below line
        ///set _act=0
        ///
        ///::  To r [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string KMS38_Activation {
            get {
                return ResourceManager.GetString("KMS38_Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @set masver=2.5
        ///@setlocal DisableDelayedExpansion
        ///@echo off
        ///
        ///
        ///
        ///::============================================================================
        ///::
        ///::   This script is a part of &apos;Microsoft_Activation_Scripts&apos; (MAS) project.
        ///::
        ///::   Homepage: mass grave[.]dev
        ///::      Email: windowsaddict@protonmail.com
        ///::
        ///::============================================================================
        ///
        ///
        ///
        ///::  To activate Office with Ohook activation, run the script with &quot;/Ohook&quot; parameter or change 0 to 1 in below [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Ohook_Activation_AIO {
            get {
                return ResourceManager.GetString("Ohook_Activation_AIO", resourceCulture);
            }
        }
    }
}
